# ============================================================================
# KWave.jl — Continuous wave propagation solvers
# ============================================================================

"""
    acoustic_field_propagator(kgrid, medium, source_amp, source_phase, freq;
                              grid_expansion=20)

Compute the steady-state acoustic field for a CW source.

Uses the Green's function approach in k-space to compute the pressure
field generated by a CW source distribution at a given frequency.

# Arguments
- `kgrid`: KWaveGrid (2D or 3D)
- `medium`: KWaveMedium
- `source_amp`: Source amplitude distribution (array matching grid size)
- `source_phase`: Source phase distribution [rad] (array matching grid size)
- `freq`: Source frequency [Hz]
- `grid_expansion`: PML/grid expansion size (default: 20)

# Returns
`(amp, phase)` — pressure amplitude and phase arrays.
"""
function acoustic_field_propagator(kgrid::KWaveGrid2D, medium::KWaveMedium,
                                   source_amp::AbstractMatrix, source_phase::AbstractMatrix,
                                   freq::Real;
                                   grid_expansion::Int=20)
    c0 = medium.sound_speed isa Real ? medium.sound_speed : mean(medium.sound_speed)
    k_freq = 2π * freq / c0

    Nx, Ny = kgrid.Nx, kgrid.Ny

    # Complex source distribution
    source = source_amp .* exp.(im .* source_phase)

    # FFT of source
    S = fft(source)

    # Green's function in k-space
    # G(kx, ky) = 1 / (k_freq^2 - kx^2 - ky^2 + i*eps)
    kx = kgrid.kx_vec
    ky = reshape(kgrid.ky_vec, 1, :)

    k_sq = kx.^2 .+ ky.^2

    # Add small absorption to avoid singularity at k = k_freq
    alpha_nepers = 0.0
    if !is_lossless(medium) && medium.alpha_coeff !== nothing
        alpha_nepers = db2neper(medium.alpha_coeff, medium.alpha_power)
    end
    eps_reg = max(alpha_nepers * k_freq, 1e-10 * k_freq^2)

    G = 1.0 ./ (k_freq^2 .- k_sq .+ im * eps_reg)

    # Propagated field
    P = S .* G
    p_field = ifft(P)

    amp = abs.(p_field)
    phase = angle.(p_field)

    return amp, phase
end

function acoustic_field_propagator(kgrid::KWaveGrid3D, medium::KWaveMedium,
                                   source_amp::AbstractArray{<:Real,3},
                                   source_phase::AbstractArray{<:Real,3},
                                   freq::Real;
                                   grid_expansion::Int=20)
    c0 = medium.sound_speed isa Real ? medium.sound_speed : mean(medium.sound_speed)
    k_freq = 2π * freq / c0

    source = source_amp .* exp.(im .* source_phase)
    S = fft(source)

    kx = kgrid.kx_vec
    ky = reshape(kgrid.ky_vec, 1, :, 1)
    kz = reshape(kgrid.kz_vec, 1, 1, :)

    k_sq = kx.^2 .+ ky.^2 .+ kz.^2

    alpha_nepers = 0.0
    if !is_lossless(medium) && medium.alpha_coeff !== nothing
        alpha_nepers = db2neper(medium.alpha_coeff, medium.alpha_power)
    end
    eps_reg = max(alpha_nepers * k_freq, 1e-10 * k_freq^2)

    G = 1.0 ./ (k_freq^2 .- k_sq .+ im * eps_reg)

    P = S .* G
    p_field = ifft(P)

    amp = abs.(p_field)
    phase = angle.(p_field)

    return amp, phase
end

"""
    angular_spectrum_cw(input_plane, dx, dy_or_nothing, freq, c0, z_pos;
                        grid_expansion=0)

Project a CW pressure field to a parallel plane using the angular spectrum method.

# Arguments
- `input_plane`: Complex pressure at the source plane (1D vector or 2D matrix)
- `dx`: Grid spacing in x [m] (or y for 1D)
- `dy_or_nothing`: Grid spacing in y [m] for 2D, or `nothing` for 1D
- `freq`: Source frequency [Hz]
- `c0`: Sound speed [m/s]
- `z_pos`: Propagation distance(s) [m] — scalar or vector

# Returns
Complex pressure field at the target plane(s).
For scalar `z_pos`: array same shape as `input_plane`.
For vector `z_pos`: array with extra dimension for each z position.
"""
function angular_spectrum_cw(input_plane::AbstractVector, dx::Real,
                             freq::Real, c0::Real, z_pos;
                             grid_expansion::Int=0)
    N = length(input_plane)
    k = 2π * freq / c0

    # Wavenumber vector
    dkx = 2π / (N * dx)
    kx = _fft_freq_vec(N) .* dkx

    # FFT of input
    P0 = fft(complex.(Float64.(input_plane)))

    if z_pos isa Real
        # Single plane
        kz = sqrt.(Complex.(k^2 .- kx.^2))
        propagator = exp.(im .* kz .* z_pos)
        return ifft(P0 .* propagator)
    else
        # Multiple planes
        result = zeros(ComplexF64, N, length(z_pos))
        for (i, z) in enumerate(z_pos)
            kz = sqrt.(Complex.(k^2 .- kx.^2))
            propagator = exp.(im .* kz .* z)
            result[:, i] = ifft(P0 .* propagator)
        end
        return result
    end
end

function angular_spectrum_cw(input_plane::AbstractMatrix, dx::Real, dy::Real,
                             freq::Real, c0::Real, z_pos;
                             grid_expansion::Int=0)
    Nx, Ny = size(input_plane)
    k = 2π * freq / c0

    dkx = 2π / (Nx * dx)
    dky = 2π / (Ny * dy)
    kx = _fft_freq_vec(Nx) .* dkx
    ky = reshape(_fft_freq_vec(Ny) .* dky, 1, :)

    P0 = fft(complex.(Float64.(input_plane)))

    kx_sq = kx.^2 .+ ky.^2

    if z_pos isa Real
        kz = sqrt.(Complex.(k^2 .- kx_sq))
        propagator = exp.(im .* kz .* z_pos)
        return ifft(P0 .* propagator)
    else
        result = zeros(ComplexF64, Nx, Ny, length(z_pos))
        for (i, z) in enumerate(z_pos)
            kz = sqrt.(Complex.(k^2 .- kx_sq))
            propagator = exp.(im .* kz .* z)
            result[:, :, i] = ifft(P0 .* propagator)
        end
        return result
    end
end

# Uses _fft_freq_vec from reconstruction/fft_recon.jl
